### ISSUE TITLE
Problem about Mqtt-Bridge

### ISSUE THREAD

**Issue by SmartRobotCompany** [rt-net/thouzer_ros#1]
Excuse me
I have the thouzer with mqtt Api
And I want to build the thouzer as ROS car
I refer your code to build ROS system
But I am facing the problem about mqtt-bridge now

Below is my mqtt.yaml setting:

```
mqtt:
  client:
    protocol: 4
  connection:
    host: 192.168.212.1
    port: 1883
    keepalive: 60
  account:
    username: "thouzer"
    password: "thouzer"
 
  serializer: json:dumps
  deserializer: json:loads
  
  bridge:
    - factory: mqtt_bridge.bridge:RosToMqttBridge
      msg_type: thouzer_msgs.msg:Vel
      topic_from: 0/WHISPERER/RMS-10E1-AAO09/vel2D_DWO
      topic_to: /thouzer/formatted_vel
```

And this is my python code:

```
 class MqttTest():

      def __init__(self):
          self.sub_cmd  = rospy.Subscriber('/thouzer/formatted_vel', Vel, self._on_callback_vel, queue_size=1)
          self.cmd_vel_publisher = rospy.Publisher('/cmd_vel', Twist, queue_size=10)
          self.v = 0.0
          self.w = 0.0

      def _on_callback_vel(self, msg):
          self.v = msg.v_mps
          self.w = msg.w_degps
          self.publish_cmd_vel(self.v, self.w)
    
      def publish_cmd_vel(self, linear_vel, angular_vel):
          twist_msg = Twist()
          twist_msg.linear.x = linear_vel
          twist_msg.angular.z = angular_vel
          self.cmd_vel_publisher.publish(twist_msg)
    

  def main():
      rospy.init_node('thouzer_cmd_vel')
      mqtt_test = MqttTest()
      rospy.spin()
    
  if __name__ == "__main__":
     main()
```
   
The problem I faces is that I can't receive any message from topic '/thouzer/formatted_vel' 
I have check that the mqtt is connect successly, and command Mqtt api directly successly too
May I ask how you use the mqtt-bridge?

Thank you!!
